FROM node:16 as build

RUN npm install -g @angular/cli@14

WORKDIR /app

COPY ./package.json .

RUN npm install

COPY . .

EXPOSE 4200
EXPOSE 49153

CMD ["ng" , "serve", "--host",  "0.0.0.0", "--poll" , "500" ]

